app/views/home/index.html.erb
app/views/layouts/components/_paragraph.html.erb

Adds a component for paragraphs

[20] Add paragraph component

---

app/assets/stylesheets/gov.scss
app/assets/stylesheets/header.scss
app/assets/stylesheets/image.scss
app/views/case_study/show.html.erb
app/views/layouts/components/images/_hero.html.erb

[24] Add hero image

---

app/assets/stylesheets/quote.scss
app/assets/stylesheets/text.scss
app/views/case_study/show.html.erb
app/views/home/index.html.erb
app/views/layouts/components/_quote.html.erb
app/views/layouts/components/_testimonial.html.erb

[15] Add testimonial component

---

lib/gateway/contentful_gateway.rb
spec/acceptance/get_case_study_spec.rb
spec/fixtures/contentful/case_studies/case_study_acceptance.json
spec/fixtures/contentful/case_studies/case_study_example_one.json
spec/fixtures/contentful/case_studies/case_study_example_two.json
spec/unit/gateway/contentful_gateway_spec.rb

Adding testimonials to case study gateway and use case

Add testimonials to casestudy gateway

---

app/assets/stylesheets/home.scss
app/assets/stylesheets/link.scss
app/assets/stylesheets/sub-category.scss
app/assets/stylesheets/text.scss
app/controllers/sub_category_controller.rb
app/views/case_study/show.html.erb
app/views/error/404.html.erb
app/views/home/index.html.erb
app/views/layouts/application.html.erb
app/views/sub_category/index.html.erb
app/views/tvs/index.html.erb
config/routes.rb

[37] Create sub-category page

---

app/controllers/category_controller.rb
app/views/category/index.html.erb
config/routes.rb
lib/domain/category.rb
lib/gateway/contentful_gateway.rb

[33] Create category page

---

app/views/tvs/index.html.erb

[39] Add hero image to teaching vacancies page

---

app/assets/stylesheets/footer.scss
app/assets/stylesheets/header.scss
app/controllers/home_controller.rb
app/views/home/index.html.erb
app/views/home/placeholder.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/components/_link.html.erb
app/views/layouts/components/links/_external.html.erb
app/views/layouts/components/links/_internal.html.erb
config/routes.rb

- Adds links to existing guidence/content where available
- Adds placeholder links where content is yet to be created/unknown
- Adds internal/external link components

[38] Add links to the homepage & nav bar

---

Gemfile
Gemfile.lock
app/views/layouts/renderers/_component_renderer.html.erb
lib/gateway/contentful_gateway.rb
spec/acceptance/get_case_study_spec.rb
spec/fixtures/contentful/case_studies/case_study_acceptance.json
spec/fixtures/contentful/case_studies/case_study_example_one.json
spec/fixtures/contentful/case_studies/case_study_example_two.json
spec/fixtures/contentful/case_studies/case_study_with_rich_text.json
spec/unit/gateway/contentful_gateway_spec.rb

- only support paragraphs and links for now

[84] Support rich text fields from contentful

---

app/assets/stylesheets/case_study.scss
app/views/layouts/components/_container.html.erb
app/views/layouts/renderers/_component_renderer.html.erb
lib/gateway/contentful_gateway.rb
spec/fixtures/contentful/case_studies/case_study_example_one.json
spec/fixtures/contentful/case_studies/case_study_example_two.json
spec/unit/gateway/contentful_gateway_spec.rb

[69] Add container handling in Contentful gateway

---

lib/gateway/contentful_gateway.rb
spec/fixtures/contentful/case_studies/case_study_with_rich_text.json
spec/fixtures/contentful/case_studies/expected_html_case_study_with_rich_text.html
spec/unit/gateway/contentful_gateway_spec.rb

[96] Add heading, paragraph and bullet lists rich text renderers

---

app/assets/stylesheets/lists.scss
app/views/layouts/components/bullet_lists/_ordered_bullet_list.html.erb

Fix nested unordered lists in large numbers list

---

robots.txt

adding robots.txt file to stop indexing

[110] add robots.txt to stop indexing

---

app/views/category/hiring.html.erb
app/views/layouts/components/_image_link_with_description.html.erb

[119] Refactor hiring page to use image link component

---

app/assets/stylesheets/text.scss
app/views/sub_category/index.html.erb

Update sub-category link and heading column width

---

app/views/resource/retro.html.erb

edit retro resource layout

---

app/views/resource/retro.html.erb

Update headings and column width of retro resource page

---

app/controllers/resource_controller.rb
app/views/resource/ecf_rollout.html.erb
config/routes.rb

[135] add ECF roll out page

---

app/views/resource/ecf_rollout.html.erb
app/views/resource/manage_behaviour.html.erb
app/views/resource/respect_and_trust.erb
app/views/resource/retro.html.erb
app/views/resource/teaching_assistants.html.erb

[133] Edit resource breadcrumbs

---

app/assets/stylesheets/image.scss

Add min height for default images

---

app/assets/stylesheets/lists.scss

Fix margin left on bullet lists in containers

---

app/assets/stylesheets/lists.scss

Fix position of large numbers in ordered lists

---

app/controllers/resource_controller.rb
app/views/resource/ground_rules.html.erb
config/routes.rb

found at `/resource/using-ground-rules-to-create-a-culture-of-respect-and-trust`

add ground rules resource page

---

app/views/resource/respect_and_trust.erb
config/routes.rb

Renaming the `How to create a culture of respect and trust` resource  to `Using meditation to create a culture of respect and trust` .

[167] edit respect and trust resource

---

app/views/layouts/_bottom_nav.html.erb

[185] Refactor bottom nav to use govuk-list
